export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@goparticipate/auth/edge";
import { connectPlatformDB, MagicCode } from "@goparticipate/db";
import { generateCode, hashCode } from "@goparticipate/auth";
import { Types } from "mongoose";

// POST /api/auth/player-code — parent or coach generates a temporary code for a player
// The player enters this code to get a scoped session (view their team, schedule, stats)
export async function POST(req: NextRequest): Promise<NextResponse> {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await req.json();
  const { playerId, familyId } = body;

  if (!playerId) {
    return NextResponse.json({ error: "playerId is required" }, { status: 400 });
  }

  await connectPlatformDB();

  const code = generateCode();
  const hashed = await hashCode(code);

  // Player access codes last 24 hours (longer than login codes)
  const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000);

  await MagicCode.create({
    identifier: `player:${playerId}`,
    identifierType: "phone", // not really phone, just a tag
    code, // store plaintext for dev display — in prod the parent shares it verbally/text
    hashedCode: hashed,
    expiresAt,
    purpose: "player_access",
    generatedBy: new Types.ObjectId(session.user.id),
    familyId: familyId ? new Types.ObjectId(familyId) : undefined,
    playerId: new Types.ObjectId(playerId),
    scopedRole: "player_view",
  });

  return NextResponse.json({
    code,
    expiresAt,
    playerId,
    message: "Share this code with the player. They can enter it on the login screen to view their team info.",
  });
}

// GET /api/auth/player-code — list active codes generated by this user
export async function GET(req: NextRequest): Promise<NextResponse> {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  await connectPlatformDB();

  const codes = await MagicCode.find({
    generatedBy: new Types.ObjectId(session.user.id),
    purpose: "player_access",
    expiresAt: { $gt: new Date() },
    usedAt: null,
  })
    .select("code playerId expiresAt createdAt")
    .sort({ createdAt: -1 })
    .lean();

  return NextResponse.json(codes);
}
